INSERT INTO `quizzes` (`id`, `FK_users`, `FK_categories`, `scores`)
VALUES

(NULL, '1', '4', '.80'),
(NULL, '1', '2', '.73'),
(NULL, '1', '7', '.91'),
(NULL, '1', '1', '.52'),
(NULL, '1', '5', '.43'),
(NULL, '1', '3', '.39'),
(NULL, '1', '0', '.08'),
(NULL, '1', '8', '.10'),
(NULL, '1', '6', '.65'),
(NULL, '1', '4', '.25'),
(NULL, '1', '1', '1.0'),
(NULL, '1', '7', '.84'),
(NULL, '1', '3', '.72'),
(NULL, '1', '2', '.62'),
(NULL, '1', '5', '.51'),
(NULL, '1', '8', '.44'),
(NULL, '1', '6', '.37'),
(NULL, '1', '2', '.22'),
(NULL, '1', '4', '.10'),
(NULL, '1', '0', '.05'),
(NULL, '1', '8', '.96'),
(NULL, '1', '4', '.82'),
(NULL, '1', '2', '.70'),
(NULL, '1', '7', '.98'),
(NULL, '1', '1', '.50'),
(NULL, '1', '5', '.43'),
(NULL, '1', '3', '.31'),
(NULL, '1', '0', '.02'),
(NULL, '1', '8', '.19'),
(NULL, '1', '6', '.68'),
(NULL, '1', '4', '.20'),
(NULL, '1', '1', '1.7'),
(NULL, '1', '7', '.80'),
(NULL, '1', '3', '.76'),
(NULL, '1', '2', '.65'),
(NULL, '1', '5', '.50'),
(NULL, '1', '8', '.40'),
(NULL, '1', '6', '.34'),
(NULL, '1', '2', '.20'),
(NULL, '1', '4', '.10'),
(NULL, '1', '0', '.03'),
(NULL, '1', '8', '.90'),
(NULL, '1', '4', '.80'),
(NULL, '1', '2', '.76'),
(NULL, '1', '7', '.90'),
(NULL, '1', '1', '.50'),
(NULL, '1', '5', '.48'),
(NULL, '1', '3', '.32'),
(NULL, '1', '0', '.00'),
(NULL, '1', '8', '.10'),
(NULL, '1', '6', '.63'),
(NULL, '1', '4', '.20'),
(NULL, '1', '1', '1.0'),
(NULL, '1', '7', '.81'),
(NULL, '1', '3', '.70'),
(NULL, '1', '2', '.60'),
(NULL, '1', '5', '.51'),
(NULL, '1', '8', '.42'),
(NULL, '1', '6', '.33'),
(NULL, '1', '2', '.24'),
(NULL, '1', '4', '.16'),
(NULL, '1', '0', '.05'),
(NULL, '1', '8', '.97'),
(NULL, '1', '4', '.86'),
(NULL, '1', '2', '.78'),
(NULL, '1', '7', '.99'),
(NULL, '1', '1', '.51'),
(NULL, '1', '5', '.42'),
(NULL, '1', '3', '.30'),
(NULL, '1', '0', '.03'),
(NULL, '1', '8', '.10'),
(NULL, '1', '6', '.65'),
(NULL, '1', '4', '.26'),
(NULL, '1', '1', '1.0'),
(NULL, '1', '7', '.86'),
(NULL, '1', '3', '.77'),
(NULL, '1', '2', '.68'),
(NULL, '1', '5', '.59'),
(NULL, '1', '8', '.40'),
(NULL, '1', '6', '.31'),
(NULL, '1', '2', '.22'),
(NULL, '1', '4', '.13'),
(NULL, '1', '0', '.04'),
(NULL, '1', '8', '.95'),
(NULL, '1', '4', '.86'),
(NULL, '1', '2', '.77'),
(NULL, '1', '7', '.98'),
(NULL, '1', '1', '.59'),
(NULL, '1', '5', '.40'),
(NULL, '1', '3', '.31'),
(NULL, '1', '0', '.02'),
(NULL, '1', '8', '.13'),
(NULL, '1', '6', '.68'),
(NULL, '1', '4', '.23'),
(NULL, '1', '1', '1.0'),
(NULL, '1', '7', '.82'),
(NULL, '1', '3', '.71'),
(NULL, '1', '2', '.64'),
(NULL, '1', '5', '.55'),
(NULL, '1', '8', '.42'),
(NULL, '1', '6', '.37'),
(NULL, '1', '2', '.28'),
(NULL, '1', '4', '.15'),
(NULL, '1', '0', '.03'),
(NULL, '1', '8', '.92');


INSERT INTO `questions` (`id`, `question`, `FK_categories`)
VALUES

(NULL, 'Which is the most famous soccer team in Germany?', '2'),
(NULL, 'Who is the best soccer player in the world?', '2'),
(NULL, 'What sport was brought to Japan by the Americans during World War 2?', '2'),
(NULL, 'Which NBA basketball team is from New York?', '2'),
(NULL, 'How many points are scored for a free-throw shot in basketball?', '2'),
(NULL, 'Which baseball team is from New York?', '2'),
(NULL, 'Which hockey team is from New York City?', '2'),
(NULL, 'What is the primary color of Bayern Munchen?', '2'),
(NULL, 'How many players are on the field for the defensive team in baseball?', '2'),
(NULL, 'How many quarterbacks are on the field in American Football?', '2'),
(NULL, 'How many points are scored from one Touchdown in American Football?', '2'),
(NULL, 'How many runs are scored in baseball from a Grand Slam?', '2'),
(NULL, 'Who was the 44th President of the USA?', '3'),
(NULL, 'Who was the 43rd President of the USA?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '3'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '4'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '5'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '6'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '7'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8'),
(NULL, 'test question?', '8');



INSERT INTO `answers` (`id`, `answer`, `FK_question`, `correct`)
VALUES

(NULL, 'test correct', '38', '1'),
(NULL, 'test correct', '39', '1'),
(NULL, 'test correct', '40', '1'),
(NULL, 'test correct', '41', '1'),
(NULL, 'test correct', '42', '1'),
(NULL, 'test correct', '43', '1'),
(NULL, 'test correct', '44', '1'),
(NULL, 'test correct', '45', '1'),
(NULL, 'test correct', '46', '1'),
(NULL, 'test correct', '47', '1'),
(NULL, 'test correct', '48', '1'),
(NULL, 'test correct', '49', '1'),
(NULL, 'test correct', '41', '1'),
(NULL, 'test correct', '50', '1'),
(NULL, 'test correct', '51', '1'),
(NULL, 'test correct', '52', '1'),
(NULL, 'test correct', '53', '1'),
(NULL, 'test correct', '54', '1'),
(NULL, 'test correct', '55', '1'),
(NULL, 'test correct', '56', '1'),
(NULL, 'test correct', '57', '1'),
(NULL, 'test correct', '58', '1'),
(NULL, 'test correct', '59', '1'),
(NULL, 'test correct', '60', '1'),
(NULL, 'test correct', '61', '1'),
(NULL, 'test correct', '62', '1'),
(NULL, 'test correct', '63', '1'),
(NULL, 'test correct', '64', '1'),
(NULL, 'test correct', '65', '1'),
(NULL, 'test correct', '66', '1'),
(NULL, 'test correct', '67', '1'),
(NULL, 'test correct', '68', '1'),
(NULL, 'test correct', '69', '1'),
(NULL, 'test correct', '70', '1'),
(NULL, 'test correct', '71', '1'),
(NULL, 'test correct', '72', '1'),
(NULL, 'test correct', '73', '1'),
(NULL, 'test correct', '74', '1'),
(NULL, 'test correct', '75', '1'),
(NULL, 'test correct', '76', '1'),
(NULL, 'test correct', '77', '1'),
(NULL, 'test correct', '78', '1'),
(NULL, 'test correct', '79', '1'),
(NULL, 'test correct', '80', '1'),
(NULL, 'test correct', '81', '1'),
(NULL, 'test correct', '82', '1'),
(NULL, 'test correct', '83', '1'),
(NULL, 'test correct', '84', '1'),
(NULL, 'test correct', '85', '1'),
(NULL, 'test correct', '86', '1'),
(NULL, 'test correct', '87', '1'),
(NULL, 'test correct', '88', '1'),
(NULL, 'test correct', '89', '1'),
(NULL, 'test correct', '90', '1'),
(NULL, 'test correct', '91', '1'),
(NULL, 'test correct', '92', '1'),
(NULL, 'test correct', '93', '1'),
(NULL, 'test correct', '94', '1'),
(NULL, 'test correct', '95', '1'),
(NULL, 'test correct', '96', '1'),
(NULL, 'test correct', '97', '1'),
(NULL, 'test correct', '98', '1'),
(NULL, 'test correct', '99', '1'),
(NULL, 'test correct', '100', '1'),
(NULL, 'test correct', '101', '1'),
(NULL, 'test correct', '102', '1'),
(NULL, 'test correct', '103', '1'),
(NULL, 'test correct', '104', '1'),
(NULL, 'test correct', '105', '1'),
(NULL, 'test correct', '106', '1'),
(NULL, 'test correct', '107', '1');


INSERT INTO `answers` (`id`, `answer`, `FK_question`, `correct`)
VALUES
(NULL, 'wrong7', '38', '0'),
(NULL, 'wrong7', '39', '0'),
(NULL, 'wrong7', '40', '0'),
(NULL, 'wrong7', '41', '0'),
(NULL, 'wrong7', '42', '0'),
(NULL, 'wrong7', '43', '0'),
(NULL, 'wrong7', '44', '0'),
(NULL, 'wrong7', '45', '0'),
(NULL, 'wrong7', '46', '0'),
(NULL, 'wrong7', '47', '0'),
(NULL, 'wrong7', '48', '0'),
(NULL, 'wrong7', '49', '0'),
(NULL, 'wrong7', '41', '0'),
(NULL, 'wrong7', '50', '0'),
(NULL, 'wrong7', '51', '0'),
(NULL, 'wrong7', '52', '0'),
(NULL, 'wrong7', '53', '0'),
(NULL, 'wrong7', '54', '0'),
(NULL, 'wrong7', '55', '0'),
(NULL, 'wrong7', '56', '0'),
(NULL, 'wrong7', '57', '0'),
(NULL, 'wrong7', '58', '0'),
(NULL, 'wrong7', '59', '0'),
(NULL, 'wrong7', '60', '0'),
(NULL, 'wrong7', '61', '0'),
(NULL, 'wrong7', '62', '0'),
(NULL, 'wrong7', '63', '0'),
(NULL, 'wrong7', '64', '0'),
(NULL, 'wrong7', '65', '0'),
(NULL, 'wrong7', '66', '0'),
(NULL, 'wrong7', '67', '0'),
(NULL, 'wrong7', '68', '0'),
(NULL, 'wrong7', '69', '0'),
(NULL, 'wrong7', '70', '0'),
(NULL, 'wrong7', '71', '0'),
(NULL, 'wrong7', '72', '0'),
(NULL, 'wrong7', '73', '0'),
(NULL, 'wrong7', '74', '0'),
(NULL, 'wrong7', '75', '0'),
(NULL, 'wrong7', '76', '0'),
(NULL, 'wrong7', '77', '0'),
(NULL, 'wrong7', '78', '0'),
(NULL, 'wrong7', '79', '0'),
(NULL, 'wrong7', '80', '0'),
(NULL, 'wrong7', '81', '0'),
(NULL, 'wrong7', '82', '0'),
(NULL, 'wrong7', '83', '0'),
(NULL, 'wrong7', '84', '0'),
(NULL, 'wrong7', '85', '0'),
(NULL, 'wrong7', '86', '0'),
(NULL, 'wrong7', '87', '0'),
(NULL, 'wrong7', '88', '0'),
(NULL, 'wrong7', '89', '0'),
(NULL, 'wrong7', '90', '0'),
(NULL, 'wrong7', '91', '0'),
(NULL, 'wrong7', '92', '0'),
(NULL, 'wrong7', '93', '0'),
(NULL, 'wrong7', '94', '0'),
(NULL, 'wrong7', '95', '0'),
(NULL, 'wrong7', '96', '0'),
(NULL, 'wrong7', '97', '0'),
(NULL, 'wrong7', '98', '0'),
(NULL, 'wrong7', '99', '0'),
(NULL, 'wrong7', '100', '0'),
(NULL, 'wrong7', '101', '0'),
(NULL, 'wrong7', '102', '0'),
(NULL, 'wrong7', '103', '0'),
(NULL, 'wrong7', '104', '0'),
(NULL, 'wrong7', '105', '0'),
(NULL, 'wrong7', '106', '0'),
(NULL, 'wrong7', '107', '0');







